### ISSUE TITLE
Design wireframe

### ISSUE THREAD

**Issue by nmpereira** [intelagense/countmedown#11]

**Comment by Carlabreis** [comment]
I want to contribute

**Comment by gitcyco** [comment]
Assign me.

**Comment by nmpereira** [comment]
![image](https://user-images.githubusercontent.com/45009203/171068763-b47eea83-ffd2-4778-9483-afce06e0b01a.png)

**Comment by ajnage** [comment]
pls add  me

**Comment by sullivanEmerald** [comment]
please add me

**Comment by abena-wf** [comment]
add me

**Comment by nebulahh** [comment]
hello

**Comment by nmpereira** [comment]
![image](https://user-images.githubusercontent.com/45009203/171073364-708d3193-e4f0-4ee8-8429-92297f2ca5ef.png)
