### ISSUE TITLE
Create express server and basic routes

### ISSUE THREAD

**Issue by intelagense** [intelagense/countmedown#2]
create express server, specify port (process.env.port)

Routes:
get /task
get /task/:id
post /task
patch /task/:id
delete /task/:id

**Comment by ajnage** [comment]
pls assign to me

**Comment by Carlabreis** [comment]
Please, assign to me.

**Comment by nebulahh** [comment]
hey

**Comment by sullivanEmerald** [comment]
please assign me

**Comment by intelagense** [comment]
Great work team!
